# Generated by Django 4.2.1 on 2023-06-12 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chartapp", "0006_product_full_category_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logs",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_adding",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2023, 6, 12, 10, 9, 8, 50302),
                    ),
                ),
                ("logString", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="date_of_last_one",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 6, 12, 10, 9, 8, 50302)
            ),
        ),
    ]
