# Generated by Django 4.2.1 on 2023-06-12 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chartapp", "0007_logs_alter_product_date_of_last_one"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logs",
            name="date_of_adding",
        ),
        migrations.AddField(
            model_name="logs",
            name="date_of_event",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 6, 12, 12, 44, 52, 435129)
            ),
        ),
        migrations.AddField(
            model_name="logs",
            name="event_Type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="date_of_last_one",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 6, 12, 12, 44, 52, 435129)
            ),
        ),
    ]
