# Generated by Django 4.2.1 on 2023-05-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chartapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("date", models.DateTimeField()),
            ],
        ),
    ]
