# Generated by Django 4.2.1 on 2023-05-29 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chartapp", "0004_delete_tact"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="date_of_last_one",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
