# Generated by Django 4.2.1 on 2023-06-12 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chartapp", "0005_product_date_of_last_one"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="full_category_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="date_of_last_one",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 6, 12, 9, 3, 15, 3273)
            ),
        ),
    ]
