# Generated by Django 4.2.1 on 2023-06-13 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chartapp", "0008_remove_logs_date_of_adding_logs_date_of_event_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="logs",
            name="product_id",
            field=models.IntegerField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="logs",
            name="date_of_event",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 6, 13, 10, 15, 11, 763729)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="date_of_last_one",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 6, 13, 10, 15, 11, 763729)
            ),
        ),
    ]
