# Generated by Django 4.2.1 on 2023-07-03 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chartapp", "0010_alter_logs_date_of_event_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="logs",
            name="ip",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="logs",
            name="date_of_event",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 7, 3, 10, 55, 27, 438177)
            ),
        ),
        migrations.AlterField(
            model_name="logs",
            name="product_id",
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="product",
            name="date_of_last_one",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
