# Generated by Django 4.2.1 on 2023-08-31 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chartapp", "0012_example_data_alter_logs_date_of_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logs",
            name="date_of_event",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 8, 31, 8, 34, 46, 76876)
            ),
        ),
    ]
